import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { ThemeProvider } from "next-themes";
import { ThemeProvider } from "@/components/theme/ThemeContext";
import Header from "@/components/header";
// import { PersistGate } from "redux-persist/integration/react";
// import { store, persistor } from "@/lib/store";
// import { Provider } from "react-redux";
import ReduxProvider from "./reduxProvider";
import Footer from "@/components/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col antialiased`}
      >
        <ReduxProvider>
          <ThemeProvider>
            <Header />
            <main className="flex-1 ml-5 mr-5"> {children}</main>
            <Footer />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
